update create, add delete,update operation
E24U/ms-article pull request #3
Opened 2022-08-26 03:38 UTC by AMakutsevi4

2022-08-26 06:58 UTC, Vasilenko773 requested changes
Исправить маленькие замечания

2022-08-26 06:58 UTC, Vasilenko773 commented on src/main/java/ru/e24u/article/controller/ArticleController.java
>      @ResponseStatus(HttpStatus.OK)
Удалить везде ResponseStatus так как ты и используешь RestController

2022-08-26 06:58 UTC, Vasilenko773 commented on src/main/java/ru/e24u/article/controller/ArticleController.java
> +    public void delete(@PathVariable long id) {
Изменить все @PathVariable на @RequestParam, так как @RequestParam - хорошая практика, увеличивающая надежность запросов

2022-08-26 17:57 UTC, MerkurevSergei approved these changes

2022-08-26 17:57 UTC, MerkurevSergei commented on src/main/java/ru/e24u/article/controller/ArticleController.java
> +    public void delete(@PathVariable long id) {
Не понял, почему?

2022-08-26 17:57 UTC, MerkurevSergei commented on src/main/java/ru/e24u/article/controller/ArticleController.java
>      @ResponseStatus(HttpStatus.OK)
Ну есть ли большой смысл удалять, я бы не акцентировался на этом

2022-08-27 12:13 UTC, MerkurevSergei approved these changes

2022-08-27 12:14 UTC, merged